spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/promptflow}
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    mapper:
      sort-properties-alphabetically: false

server:
  port: 8080

logging:
  level:
    org.sieun.prompt2animation: DEBUG


openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-5.4-mini

kie:
  api-key: ${KIE_API_KEY}
  model: google/nano-banana
  video-model: kling-2.6/image-to-video

storage:
  upload-dir: uploads/results

app:
  base-url: http://localhost:8080